# Generated by Django 3.0 on 2020-01-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_customers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('PurchasePrice', models.CharField(max_length=100)),
                ('SalesPrice', models.CharField(max_length=100)),
                ('Tax', models.CharField(max_length=100)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
    ]
