# Generated by Django 3.0 on 2020-01-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200127_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='users',
        ),
    ]
