# Generated by Django 3.0 on 2020-01-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_customers_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customers',
        ),
    ]
