# Generated by Django 3.0 on 2020-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='vendorName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
