# Generated by Django 3.0 on 2020-01-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_bill_vendor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='vendor_name',
        ),
    ]
