# Generated by Django 3.0 on 2020-01-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='users',
        ),
    ]
