# Generated by Django 3.0 on 2020-01-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_customers_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customers',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='users',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
