# Generated by Django 3.0 on 2020-01-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
    ]
