# Generated by Django 3.0 on 2020-01-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_bill_vendorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='vendorName',
        ),
    ]
