# Generated by Django 3.0 on 2020-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_bill_vendorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='vendor_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
