# Generated by Django 3.0 on 2020-02-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('purchase_price', models.CharField(max_length=100)),
                ('sales_price', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
