# Generated by Django 3.0 on 2020-02-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20200206_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_date',
            new_name='billDate',
        ),
    ]
